export const promoText = `_This post was generated by the Label Studio Archive Bot from a conversation in the [Label Studio Slack](https://slack.labelstud.io/?source=discourse), a gathering place for the Label Studio community. Someone in the community thought this was worth sharing!_
  
_If this post answered a question for you, hit the Like button - we use that to assess which posts to put into docs._`;
