name: "Deploy env"

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Docker image version'
        required: true
        type: string

env:
  HELM_RELEASE_NAMESPACE: slack-archivist
  IMAGE_NAME: "heartexlabs/slack-archivist"
  AWS_EKS_REGION: "us-east-1"
  AWS_EKS_CLUSTER_NAME: "dev-lse-eks-cluster"

jobs:

  deploy:
    name: "Environment"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: 'arn:aws:iam::726004645192:role/github-runner'
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ env.AWS_EKS_REGION }}

      - name: Configure kubeconfig
        shell: bash
        run: |
          aws eks update-kubeconfig \
            --region '${{ env.AWS_EKS_REGION }}' \
            --name '${{ env.AWS_EKS_CLUSTER_NAME }}' \
            --alias '${{ env.AWS_EKS_CLUSTER_NAME }}'

      - name: Upgrade
        run: kubectl -n '${{ env.HELM_RELEASE_NAMESPACE }}' set image deployment/slack-archivist slack-archivist=${{ env.IMAGE_NAME }}:${{ inputs.image_version }}
